### PR TITLE
Frontend patch

### PR DESCRIPTION
**Pull request by jonator**
Please test and point out stuff we dont have!

### CODE REVIEW

**Comment by alexwendte** [comment]
- divide the price and cost to produce you are receiving by 100 in order to display in dollars properly
- multiply the result when an admin updates the price or cost to produce by 100 in order to send the amount to the server properly in cents
- when you update a card the card's imageUrl is cut short for some reason
- pressing Purchase Cart does not clear a user's cart items on the frontend (it does in the database)

**Comment by jonator** [comment]
@alexwendte I do tell the user to enter price in cents, they will update it in cents also

**Comment by alexwendte** [comment]
When a card is updated, if I enter: 3.00 for a $3.00 card, .03 is sent to the database. We are not able to display anything to the user, because the previous dollar value of the cart is in the input spot. Could you just multiply that value by 100 so 300 cents gets sent to the server instead of 3 cents

**Comment by jonator** [comment]
> pressing Purchase Cart does not clear a user's cart items on the frontend (it does in the database)

Just tested this and it was working for me

**Comment by alexwendte** [comment]
> > pressing Purchase Cart does not clear a user's cart items on the frontend (it does in the database)
> > Just tested this and it was working for me

Yep, it does for me now too!

**Comment by jonator** [comment]
> When a card is updated, if I enter: 3.00 for a $3.00 card, .03 is sent to the database. We are not able to display anything to the user, because the previous dollar value of the cart is in the input spot. Could you just multiply that value by 100 so 300 cents gets sent to the server instead of 3 cents

I'm confused by this, is this just when the admin is updating an existing card?

**Comment by jonator** [comment]
Still getting problems with new card img url getting cut off for some reason..

**Pull request merged**
